### ISSUE TITLE
Got an error reponse from sidecar

### ISSUE THREAD

**Issue by Ljzn** [yangwao/substrate_playground#1]
**Description**

- Set up an mainnet edgeware node with this: https://github.com/yangwao/substrate_playground
- Start [sidecar](https://github.com/paritytech/substrate-api-sidecar) connecting to the websocket port of node
- visit `/blocks/head`
- got an error response

```json
{"code":500,"message":"Cannot read property 'extrinsicBaseWeight' of undefined","stack":"TypeError: Cannot read property 'extrinsicBaseWeight' of undefined\n    at BlocksService.createCalcFee (/usr/src/app/build/src/services/blocks/BlocksService.js:231:55)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async BlocksService.fetchBlock (/usr/src/app/build/src/services/blocks/BlocksService.js:55:52)\n    at async BlocksController.getLatestBlock (/usr/src/app/build/src/controllers/blocks/BlocksController.js:77:49)\n    at async /usr/src/app/build/src/controllers/AbstractController.js:138:9","level":"error"}
```

**Expected vs. Actual Behavior**

Get correct chain head block.

**Comment by yangwao** [comment]
Hello @Ljzn not sure if it's not an issue of sidecar! Just found there are some deprecation note https://github.com/paritytech/substrate-api-sidecar#note 
I can check on this later! Meanwhile, feel free to join our Builders channel, https://t.me/edg_developers

**Comment by Ljzn** [comment]
I also opened an issue under sidecar: https://github.com/paritytech/substrate-api-sidecar/issues/329
